# Generated by Django 2.0.2 on 2018-02-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybor_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankieter.Pytanie')),
            ],
        ),
    ]
