# Generated by Django 2.0.2 on 2018-02-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0003_auto_20180228_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pytanie',
            options={'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
    ]
