# Generated by Django 2.0.2 on 2018-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0004_auto_20180228_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wybor',
            options={'verbose_name': 'Wybor', 'verbose_name_plural': 'Wybory'},
        ),
    ]
