# Generated by Django 2.0.2 on 2018-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0005_auto_20180302_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='wybor',
            name='plik',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
