# Generated by Django 2.0.2 on 2018-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0006_wybor_plik'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytanie',
            name='plik',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
