# Generated by Django 2.0.2 on 2018-03-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0007_pytanie_plik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pytanie',
            old_name='plik',
            new_name='pytanie_plik',
        ),
    ]
