# Generated by Django 2.0.2 on 2018-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0009_auto_20180306_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytanie',
            name='pytanie_plik',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
