# Generated by Django 2.0.2 on 2018-03-11 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ankieter', '0010_auto_20180306_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytanie',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wybor',
            name='plik',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wybor',
            name='wybor_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
