# Generated by Django 2.0.2 on 2018-03-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0015_auto_20180313_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupa',
            name='ankieta',
        ),
        migrations.RemoveField(
            model_name='pytanie',
            name='grupa',
        ),
        migrations.DeleteModel(
            name='Ankieta',
        ),
        migrations.DeleteModel(
            name='Grupa',
        ),
    ]
