# Generated by Django 2.0.2 on 2018-03-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0016_auto_20180313_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ankieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_ankiety', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_grupy', models.CharField(default=None, max_length=30)),
                ('ankieta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ankieter.Ankieta')),
            ],
        ),
        migrations.AddField(
            model_name='pytanie',
            name='grupa',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ankieter.Grupa'),
        ),
    ]
