# Generated by Django 2.0.2 on 2018-03-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankieter', '0017_auto_20180313_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ankieta',
            options={'verbose_name': 'Ankieta', 'verbose_name_plural': 'Ankiety'},
        ),
        migrations.AlterModelOptions(
            name='grupa',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AddField(
            model_name='pytanie',
            name='ankieta',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ankieter.Ankieta'),
        ),
    ]
