# Generated by Django 2.0.2 on 2018-03-14 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ankieter', '0018_auto_20180313_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankieta',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
